package com.example.util.simpletimetracker.feature_records_filter.viewData

import com.example.util.simpletimetracker.feature_base_adapter.recordTypeSuggestion.RecordTypeSuggestionViewData

data object RecordTypeFilteredType : RecordTypeSuggestionViewData.Type